name: Node.js CI

on:
  push:
    branches:
      - main # Se activa cuando se realiza un push a la rama "main"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Especifica la versión de Node.js que necesitas

    - name: Install dependencies
      working-directory: server/
      run: npm install

    - name: Make server.js executable
      run: chmod +x ./server/server.js

    - name: Run server
      run: ./server/server.js
